import { z } from "zod";

import { completeJson, completeTextWithMetadata } from "@/lib/openrouter";
import { env } from "@/lib/env";
import { createMockChapterMemory, mergeBibleLocally } from "./mock";
import {
  buildBibleMergePrompt,
  buildExtractionPrompt,
  buildGenerationPrompt,
  buildRepairPrompt,
  buildRevisionPrompt
} from "./prompts";
import { chapterMemorySchema, storyBibleSchema, type ChapterContext, type StoryBible } from "./schema";

export async function generateDraft(params: {
  storyTitle: string;
  direction: string;
  context: ChapterContext;
}) {
  const result = await generateDraftRun(params);
  return result.content;
}

export async function generateDraftRun(params: {
  storyTitle: string;
  direction: string;
  context: ChapterContext;
}) {
  const fallback = `The page waited with the patient brightness of good paper.\n\n${params.direction}\n\nThe scene should be generated by OpenRouter when an API key is configured; for now, this local draft keeps the writing workflow alive.`;

  return completeTextWithMetadata({
    messages: [
      { role: "system", content: "You are a literary fiction co-writer who respects continuity." },
      { role: "user", content: buildGenerationPrompt(params) }
    ],
    fallback
  });
}

export async function reviseDraft(params: {
  currentDraft: string;
  command: string;
  context: ChapterContext;
}) {
  const result = await reviseDraftRun(params);
  return result.content;
}

export async function reviseDraftRun(params: {
  currentDraft: string;
  command: string;
  context: ChapterContext;
}) {
  const fallback = `${params.currentDraft}\n\n[Revision note applied locally: ${params.command}]`;

  return completeTextWithMetadata({
    messages: [
      { role: "system", content: "You revise fiction prose and return the full updated draft only." },
      { role: "user", content: buildRevisionPrompt(params) }
    ],
    fallback
  });
}

export async function extractChapterMemory(params: {
  chapterText: string;
  chapterNumber: number;
  title?: string;
  context?: ChapterContext | null;
}) {
  const fallback = createMockChapterMemory(params.chapterText, params.chapterNumber, params.title);

  try {
    return await completeJson({
      model: env.openRouterExtractModel,
      schema: chapterMemorySchema,
      format: {
        name: "ChapterMemory",
        schema: z.toJSONSchema(chapterMemorySchema) as Record<string, unknown>
      },
      messages: [
        { role: "system", content: "Return valid JSON only." },
        { role: "user", content: buildExtractionPrompt({ chapterText: params.chapterText, optionalExistingStoryContext: params.context }) }
      ],
      fallback
    });
  } catch (error) {
    if (!env.openRouterApiKey) {
      return { parsed: fallback, raw: JSON.stringify(fallback), repaired: false };
    }

    const repaired = await completeJson({
      model: env.openRouterExtractModel,
      schema: chapterMemorySchema,
      format: {
        name: "ChapterMemory",
        schema: z.toJSONSchema(chapterMemorySchema) as Record<string, unknown>
      },
      messages: [
        { role: "system", content: "Repair invalid JSON according to the required schema." },
        { role: "user", content: buildRepairPrompt(error instanceof Error ? error.message : "Unknown invalid response") }
      ],
      fallback
    });

    return { ...repaired, repaired: true };
  }
}

export async function mergeStoryBible(params: {
  existingStoryBible: StoryBible | null;
  chapterMemory: Parameters<typeof mergeBibleLocally>[1];
}) {
  const fallback = mergeBibleLocally(params.existingStoryBible, params.chapterMemory);

  try {
    return await completeJson({
      model: env.openRouterExtractModel,
      schema: storyBibleSchema,
      format: {
        name: "StoryBible",
        schema: z.toJSONSchema(storyBibleSchema) as Record<string, unknown>
      },
      messages: [
        { role: "system", content: "Return valid JSON only." },
        { role: "user", content: buildBibleMergePrompt({ existingStoryBible: params.existingStoryBible, newChapterMemory: params.chapterMemory }) }
      ],
      fallback
    });
  } catch {
    return { parsed: fallback, raw: JSON.stringify(fallback), repaired: false };
  }
}
